global.number = 0;
global.schadenmodifikator = 0;
global.volume = 50;
global.localsound = audio_play_sound(snd_level_1, 5, true);
global.wase = true;
global.dialog_index = 0;
global.dialog = ds_list_create();
ds_list_add(global.dialog, "Gegrüßt seist du," + "\n" + "Holdes Hexenweib!");
ds_list_add(global.dialog, "Planwirtschaft! ");
ds_list_add(global.dialog, "Einheit");